version: "3.1"

services:
  gocd:
    build:
      context: ./docker/gocd
    ports:
      - "8153:8153"
      - "8154:8154"
    network_mode: "host"

  goagent:
    image: gocd/gocd-agent-alpine-3.7:v18.6.0
    environment:
      - GO_SERVER_URL=https://localhost:8154/go
    network_mode: "host"
