version: "3.1"

services:
  postgres:
    build:
      context: ./docker/postgres 
    ports:
      - "5432:5432"
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD="password"
    network_mode: "host"
